name: House Rent Prediction Workflow CI

on:
  push:
    branches: [main]

jobs:
  training_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn cloudpickle

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.12.7'
          activate-environment: test

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject/ --experiment-name House_Rent_CI

      - name: Get latest MLflow run_id
        id: get_run_id
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Pastikan URI mengarah ke DagsHub agar bisa menemukan Run ID-nya
          RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/House-Rent-Prediction.mlflow'); print(mlflow.search_runs(experiment_names=['House_Rent_CI']).iloc[0]['run_id'])")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: pip install --upgrade pip

      - name: Save Artifacts to GitHub
        run: |
          mkdir -p outputs
          cp MLProject/*.png outputs/ || true

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add outputs/
          git commit -m "docs: update training artifacts [run-id ${{ env.RUN_ID }}]" || echo "No changes to commit"
          git push

      - name: Build Docker Model
        run: |
          mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/house_rent_model" -n "house-rent-image"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag house-rent-image ${{ secrets.DOCKERHUB_USERNAME }}/house-rent-prediction:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/house-rent-prediction:latest

      - name: Post Log in to Docker Hub
        run: echo "Successfully pushed to Docker Hub"

      - name: Complete job
        run: echo "Workflow finished successfully!"
