name: House Rent Prediction Workflow CI

on:
  push:
    branches: [main]

jobs:
  training_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib seaborn cloudpickle
      
      - name: Set MLflow DagsHub Env
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/levinafauziah/House-Rent-Prediction.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=levinafauziah" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/House-Rent-Prediction.mlflow
        run: |
          cd MLProject
          mlflow run . --env-manager=local > mlflow_execution.log 2>&1
          cat mlflow_execution.log

      - name: Get latest MLflow run_id
        id: get_run_id
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python -c "
          import os
          import mlflow
          mlflow.set_tracking_uri('https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/House-Rent-Prediction.mlflow')
          runs = mlflow.search_runs(experiment_names=['House_Rent_CI'])
          if not runs.empty:
              print(f'RUN_ID={runs.iloc[0].run_id}')
              with open(os.environ['GITHUB_ENV'], 'a') as f:
                  f.write(f'RUN_ID={runs.iloc[0].run_id}\n')
          "

      - name: Install Python dependencies
        run: pip install --upgrade pip

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/*.png

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
          -m runs:/${{ env.RUN_ID }}/house_rent_model \
          -n levinafauziah/house-rent-ci \
          --install-mlflow

      - name: Tag Docker Image
        run: docker tag house-rent-image ${{ secrets.DOCKERHUB_USERNAME }}/house-rent-ci:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/house-rent-ci:latest

      - name: Post Log in to Docker Hub
        run: echo "Successfully pushed to Docker Hub"

      - name: Complete job
        run: echo "Workflow finished successfully!"
