name: House Rent Prediction Workflow CI

on:
  push:
    branches: [main]

jobs:
  training_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn matplotlib seaborn cloudpickle

      - name: Set MLflow DagsHub Environment
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/levinafauziah/House-Rent-Prediction.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=levinafauziah" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local
      
      - name: Commit MLflow artifacts to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add *.png
          git commit -m "Add MLflow artifacts from CI" || echo "No changes to commit"
          git push

      - name: Get latest MLflow run id
        run: |
          python <<'EOF'
          import mlflow
          import os

          client = mlflow.tracking.MlflowClient()
          runs = client.search_runs(
              experiment_ids=["0"],
              order_by=["attributes.start_time DESC"],
              max_results=1
          )

          if not runs:
              raise RuntimeError("RUN_ID tidak ditemukan")

          run_id = runs[0].info.run_id
          print(f"RUN_ID: {run_id}")

          env_file = os.getenv('GITHUB_ENV')
          with open(env_file, "a") as f:
              f.write(f"RUN_ID={run_id}\n")
          EOF

      - name: List MLflow artifacts
        run: |
          mlflow artifacts list --run-id $RUN_ID
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: ./*.png

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            -m runs:/$RUN_ID/model \
            -n levinafauziah/house-rent-ci \
            --install-mlflow

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag levinafauziah/house-rent-ci:latest \
          ${{ secrets.DOCKERHUB_USERNAME }}/house-rent-ci:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/house-rent-ci:latest

      - name: Complete job
        run: echo "Workflow finished successfully!"